### ISSUE TITLE
请教原因 Error： read ENOTCONN

### ISSUE THREAD

**Issue by Anwy** [shen100/wemall#19]
nodejs console显示如下：
C:\Turing Projects\wemall\nodejs>node app
Server running at :8010
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: read ENOTCONN
    at _errnoException (util.js:1022:11)
    at WriteStream.Socket._read (net.js:503:20)
    at WriteStream.Readable.read (_stream_readable.js:442:10)
    at WriteStream.Socket.read (net.js:375:43)
    at resume_ (_stream_readable.js:822:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
    at Function.Module.runMain (module.js:695:11)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3 

log文件内容如下
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@5.6.0
3 info using node@v8.11.1
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle wemall@0.0.2~prestart: wemall@0.0.2
6 info lifecycle wemall@0.0.2~start: wemall@0.0.2
7 verbose lifecycle wemall@0.0.2~start: unsafe-perm in lifecycle true
8 verbose lifecycle wemall@0.0.2~start: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Turing Projects\wemall\nodejs\node_modules\.bin;C:\Users\qiuho\AppData\Roaming\npm;C:\Program Files\nodejs\;C:\Program Files\RA2HP\;C:\ProgramData\Oracle\Java\javapath;C:\windows\system32;C:\windows;C:\windows\System32\Wbem;C:\windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\nodejs\;C:\Program Files\MySQL\MySQL Utilities 1.6\;C:\Users\qiuho\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm\;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Users\qiuho\AppData\Local\Microsoft\WindowsApps;C:\Users\qiuho\AppData\Roaming\npm
9 verbose lifecycle wemall@0.0.2~start: CWD: C:\Turing Projects\wemall\nodejs
10 silly lifecycle wemall@0.0.2~start: Args: [ '/d /s /c', 'node app.js' ]
11 silly lifecycle wemall@0.0.2~start: Returned: code: 1  signal: null
12 info lifecycle wemall@0.0.2~start: Failed to exec start script
13 verbose stack Error: wemall@0.0.2 start: `node app.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:285:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid wemall@0.0.2
15 verbose cwd C:\Turing Projects\wemall\nodejs
16 verbose Windows_NT 10.0.15063
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
18 verbose node v8.11.1
19 verbose npm  v5.6.0
20 error code ELIFECYCLE
21 error errno 1
22 error wemall@0.0.2 start: `node app.js`
22 error Exit status 1
23 error Failed at the wemall@0.0.2 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by plaiuZt** [comment]
请问这个问题解决了吗，我也遇到同样的问题了
