### ISSUE TITLE
你好！，我执行 npm start 报这个错

### ISSUE THREAD

**Issue by xuqinghuo** [shen100/wemall#26]
npm start

> wemall@0.0.2 start E:\wemall\nodejs
> node app.js

Server running at :8010
events.js:180
      throw er; // Unhandled 'error' event
      ^

Error: read ENOTCONN
    at WriteStream.Socket._read (net.js:530:20)
    at WriteStream.Readable.read (_stream_readable.js:474:10)
    at resume_ (_stream_readable.js:953:12)
    at processTicksAndRejections (internal/process/task_queues.js:77:11)
Emitted 'error' event at:
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at processTicksAndRejections (internal/process/task_queues.js:77:11) {
  errno: 'ENOTCONN',
  code: 'ENOTCONN',
  syscall: 'read'
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! wemall@0.0.2 start: `node app.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the wemall@0.0.2 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     D:\nodejs\node_cache\_logs\2019-08-27T07_17_47_535Z-debug.log

**Comment by SnowfallDan** [comment]
同样！我也是这个问题卡住了

**Comment by 17768810** [comment]
原来我不是一个人。

**Comment by newjcj** [comment]
同样！我也是这个问题卡住了，怎么办

**Comment by vercharlin** [comment]
+1

**Comment by xmsalsa** [comment]
windows环境就是报这个错。

**Comment by xmsalsa** [comment]
windows环境就是报这个错。用Mac或Linux没有问题。建议用虚伪机运行。
