### ISSUE TITLE
npm start error

### ISSUE THREAD

**Issue by QQ565253906** [shen100/wemall#6]
hi shen,
我在npm start时遇到以下error,
请问可能是什么原因呢？

error log如下：
E:\Proj\wemall_clone\wemall\nodejs>npm start

> wemall@0.0.2 start E:\Proj\wemall_clone\wemall\nodejs
> node app.js

Server running at :8010
events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: read ENOTCONN
    at exports._errnoException (util.js:1016:11)
    at WriteStream.Socket._read (net.js:484:20)
    at WriteStream.Readable.read (_stream_readable.js:431:10)
    at WriteStream.Socket.read (net.js:366:43)
    at resume_ (_stream_readable.js:811:12)
    at _combinedTickCallback (internal/process/next_tick.js:102:11)
    at process._tickCallback (internal/process/next_tick.js:161:9)
    at Function.Module.runMain (module.js:607:11)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! wemall@0.0.2 start: `node app.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the wemall@0.0.2 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Administrator\AppData\Roaming\npm-cache\_logs\2017-06-25T02_18_18_865Z-debug.log

E:\Proj\wemall_clone\wemall\nodejs>

**Comment by gakaki** [comment]
你已经开了一个端啊口了 关掉再开

**Comment by QQ565253906** [comment]
你那边npm start的log是怎样的

**Comment by zhouwb168** [comment]
问题解决了吗？我也遇到了

**Comment by hairichuhe** [comment]
我也遇到了。。。。。我单独写都不行。。log是这样的
 info it worked if it ends with ok
1 verbose cli [ 'H:\\program\\nodejs\\node.exe',
1 verbose cli   'H:\\program\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@5.3.0
3 info using node@v8.2.1
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle wemall@0.0.2~prestart: wemall@0.0.2
6 info lifecycle wemall@0.0.2~start: wemall@0.0.2
7 verbose lifecycle wemall@0.0.2~start: unsafe-perm in lifecycle true
8 verbose lifecycle wemall@0.0.2~start: PATH: H:\program\nodejs\node_modules\npm\bin\node-gyp-bin;H:\gopath\code\src\wemall\nodejs\node_modules\.bin;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\ProgramData\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Common Files\microsoft shared\TigerKin;H:\program\mysql\bin;H:\program\Git\bin;H:\program\nodejs;H:\program\Python2;H:\program\redis;H:\program\TortoiseGit\bin;H:\program\go\bin;H:\program\java\sdk\platform-tools;H:\program\java\sdk\tools;H:\program\nodejs\node_global;C:\Program Files\Common Files\Autodesk Shared\;C:\Program Files (x86)\Autodesk\Backburner\;C:\Users\tc\AppData\Local\Microsoft\WindowsApps;;C:\Program Files (x86)\Microsoft VS Code\bin
9 verbose lifecycle wemall@0.0.2~start: CWD: H:\gopath\code\src\wemall\nodejs
10 silly lifecycle wemall@0.0.2~start: Args: [ '/d /s /c', 'node app.js' ]
11 silly lifecycle wemall@0.0.2~start: Returned: code: 1  signal: null
12 info lifecycle wemall@0.0.2~start: Failed to exec start script
13 verbose stack Error: wemall@0.0.2 start: `node app.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (H:\program\nodejs\node_modules\npm\lib\utils\lifecycle.js:289:16)
13 verbose stack     at emitTwo (events.js:125:13)
13 verbose stack     at EventEmitter.emit (events.js:213:7)
13 verbose stack     at ChildProcess.<anonymous> (H:\program\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
13 verbose stack     at emitTwo (events.js:125:13)
13 verbose stack     at ChildProcess.emit (events.js:213:7)
13 verbose stack     at maybeClose (internal/child_process.js:921:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
14 verbose pkgid wemall@0.0.2
15 verbose cwd H:\gopath\code\src\wemall\nodejs
16 verbose Windows_NT 10.0.15063
17 verbose argv "H:\\program\\nodejs\\node.exe" "H:\\program\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
18 verbose node v8.2.1
19 verbose npm  v5.3.0
20 error code ELIFECYCLE
21 error errno 1
22 error wemall@0.0.2 start: `node app.js`
22 error Exit status 1
23 error Failed at the wemall@0.0.2 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by hairichuhe** [comment]
@QQ565253906 你解决了吗？

**Comment by xierui921326** [comment]
@QQ565253906 我的也是和你一样的问题，你的解决了吗

**Comment by chnyx** [comment]
@QQ565253906 @xierui921326 @hairichuhe 这个问题你们解决了吗

**Comment by huanghuangzym** [comment]
遇到了同样的问题，这个问题有人解决了么 @chnyx

**Comment by plaiuZt** [comment]
遇到了同样的问题，这个问题有人解决了么 @huanghuangzym

**Comment by huanghuangzym** [comment]
> 遇到了同样的问题，这个问题有人解决了么 @huanghuangzym

我的是node版本问题，换成node8可以了

**Comment by plaiuZt** [comment]
已经是v8.9.1版本了,你具体使用的那个小版本？ @huanghuangzym

**Comment by MaiMata** [comment]
> 已经是v8.9.1版本了,你具体使用的那个小版本？ @huanghuangzym

您好，同样的问题请问怎么解决
